# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: andrucare
# "service" is the name of this project. This will also be added to your AWS resource names.
service: categoryService

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    BUCKET_NAME: !Ref CategoryImagesBucket  #get bucket name 
    DYNAMO_TABLE: !Ref CategoryTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - !Sub "${CategoryImagesBucket.Arn}/*"  #permissions for objects inside banner (operations like update object, get object)
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - !GetAtt CategoryTable.Arn

build:
  esbuild:
    bundle: true
    minify: false
    exclude:
      - "@aws-sdk/*"

resources:
  Resources:
    CategoryImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: category-images-sls-ms-ts-test

    CategoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Categories
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH


functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post

  updateCategoryImage:
    handler: handlers/updateCategoryImage.updateCategoryImage
    events:
      - s3:
          bucket: !Ref CategoryImagesBucket
          event: s3:ObjectCreated:Put #trigger event when a new object is upload to s3 bucket
          existing: true

